name: Hello World!

on:
  push:
    branches:
      - master
    paths:
      - part11/**
      - .github/workflows/hello.yml
    

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        working-directory: part11
        run: |
          ls -l