name: Bloglist Test, Build, and Publish Docker Image

on:
  push:
    branches:
      - master
    paths:
      - part7/bloglist/**
      - part7/bloglist-frontend/**
      - part7/bloglist-docker-image/**
  pull_request:
    types: [opened, synchronize]
    branches: [master]

env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}

jobs:
  bloglist-checks:
    name: Perform Bloglist App Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: npm install backend
        working-directory: part7/bloglist
        run: npm install

      - name: test backend
        working-directory: part7/bloglist
        run: npm run test

      - name: npm install frontend
        working-directory: part7/bloglist-frontend
        run: npm install

      - name: lint frontend
        working-directory: part7/bloglist-frontend
        run: npm run eslint

      - name: build frontend
        working-directory: part7/bloglist-frontend
        run: npm run build

      - name: e2e test
        uses: cypress-io/github-action@v5.0.8
        with:
          start: npm run start:test
          wait-on: http://localhost:5000
          working-directory: part7/bloglist

  push_to_registry:
    name: Push Docker image to Docker Hub
    if: ${{ github.event_name == 'push' }}
    needs: [bloglist-checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: part7/bloglist-docker-image
          push: true
          tags: |
            thefenix/bloglist:latest
            thefenix/bloglist:${{ github.sha }}
          